name: Ideas Sharing
description: Share your ideas
body:
- type: textarea
  id: info
  attributes: 
    label: Base Info
    description: About your idea...
    placeholder: Enter somethin here...
    value: |
    Suggest Name: Deep Keyboard
  Short Description: An input method with artificial intelligence that will use deep learning algorithms to anticipate the text you will type.
  Suggest programming language: C++, Python
  validations:
    required: true
- type: textarea
  id: features
  attributes: 
    label: Features
    description: About your ideas...
    placeholder: Type something here...
    value: "Anticipate the user's next input while they are typing and display it in gray text after the already typed word. When the user presses the Tab key, it will be automatically completed. It also has an automatic spelling correction function."
  validations:
    required: true
- type: textarea
  id: additional
  attributes: 
    label: Additional Text
    description: Something more
    placeholder: Enter something here...
